# Results
```{r}
library(dplyr)
library(ggplot2)
library(forcats)
library(ggmap)
library(tidyverse)
library(choroplethr)
library(vcd)
```

## Inconvience because of veganism
```{r fig.height=10,fig.width=15}
df <- read_csv('project_data/inconvience_reasons.csv')
tidydf <- df %>%
     gather(key = "opinion", value = "Counts", "Disagree", "Agree", "Neither agree nor disagree")
ggplot(
      tidydf,
      aes(Counts, 
          fct_reorder2(reason, opinion=="Disagree", Counts, .desc = FALSE),
          color = opinion)) +
      geom_point(aes(size=1)) + 
      ggtitle("Inconvience because of veganism") +
      ylab("") +
      theme_grey(16) +
      theme(plot.title = element_text(hjust = 0.5)) +
      guides(size=FALSE) 

options(repr.P.width=4,repr.P.height=10)
```

## Number of restuarants in each region
```{r fig.height=10, fig.width=10}
df_state <- read.csv("project_data/states_grouped_1.csv")
state_choropleth(df_state, title = "Number of Vegetarian restaurants in every state", legend="Counts") + scale_fill_brewer(palette=2)
```


## How many vegetarian restuarants are opened from 2014-2018

```{r}
df <- read_csv('project_data/timeseries_opening_of_restuarants.csv')
df <- df[order(df$date),]
df$tmp <- "-01"
df$date <- paste0(df$date,df$tmp)
df$date <- as.Date(df$date, format="%Y-%m-%d")
df = df[-1,]
ggplot(df, aes(date, counts, group = 1)) +
         geom_point(color="black") + 
         geom_line(colour="black") +
         geom_smooth(method ="loess",span = .3,se=FALSE, color="darkgreen") +
         scale_x_date(date_breaks = "3 month", date_labels = "%b %y") +
         labs(x = "Date", y = "Number of Vegetarain restaurants", title = "Number of Vegetarian restaurants opened over time")
```

## Length vs. Transition
```{r fig.height=10, fig.width=10}
df <- read_csv("project_data/age_transition_legth.csv")
#df$ALLTRANSITION <- as.integer(df$ALLTRANSITION)
#df$ALLLENGTH <- as.integer(df$ALLLENGTH)

mosaic(Time_for_transition ~ Length_of_veganism, labeling = vcd::labeling_border(rot_labels = c(0, 0)), df, direction=c("v","h"),main='Mosaic plot for Length and Transition to veganism')
```

## Bar plot
```{r}
df <- read_csv("project_data/age_difficulty_during_transition.csv")
df <- df[c("Age","difficulty_during_transition")]
df$difficulty_during_transition <- as.factor(df$difficulty_during_transition)
ggplot(df, aes(fct_infreq(difficulty_during_transition))) +
  geom_bar(color="darkgreen",fill = "palegreen3") + 
  ggtitle("What age group is facing a lot of difficulty during transition") +
  xlab("Opinion")+
  ylab("Count")+
  facet_wrap('Age') +
  theme_grey(14) + 
  theme(text = element_text(size=9), legend.position = "none", plot.title = element_text(hjust = 0.5))
```

```{r}
df_inc <- read_csv("project_data/age_difficulty_during_transition.csv")
df_inc
df_inc_1 <- read_csv('project_data/inconvience_reasons.csv')
```

```{r}
df_trans <- read_csv("project_data/age_transition_variables_not_modified.csv")
df_trans
```

```{r}
sapply(df_trans, class)
```


```{r}
df_trans$ALLTRANSITION <- as.factor(df_trans$ALLTRANSITION)
```
```{r}
df_trans$ALLTRANSITION <- as.factor(df_trans$ALLTRANSITION)
ggplot(df_trans, aes(x=ALLAGEADOPTION, y=ALLTRANSITION)) + geom_boxplot() + theme_grey(16) + ggtitle(" Summary of loan amounts for each level of loan purpose") + xlab("Age")  + ylab("How Long before Fully Transitioned After Deciding") + theme(text = element_text(size=9), legend.position = "none")
```

```{r}
df_trans$ALLLENGTH <- as.factor(df_trans$ALLLENGTH)
ggplot(df_trans, aes(x=ALLAGEADOPTION, y=ALLLENGTH)) + geom_boxplot() + theme_grey(16) + ggtitle(" Summary of loan amounts for each level of loan purpose") + xlab("Age")  + ylab("Length of Diet") + theme(text = element_text(size=9), legend.position = "none")
```

```{r}
df_veg_reasons <- read_csv("project_data/reasons_for_veganism.csv")
df_veg_reasons
```

```{r}
df_veg_merged <- merge(df_trans, df_veg_reasons, by = "id")
df_veg_merged
```

```{r}
chosen_cols <- c("ALLTRANSITION","ALLLENGTH", "ALLANIMALPROTECTION",
                 "ALLENVIRONMENT", "ALLCOST","ALLHEALTH",
                 "ALLRELIGIOUSSPIRITUAL", "ALLSOCIALINFLUENCE",
                 "ALLSOCIALJUSTICEWORLDHUNGER", "ALLFOODTREND",
                 "ALLDISGUST")
df_veg_merged[chosen_cols] <- lapply(df_veg_merged[chosen_cols], factor)
                 
#df_pivoted <- df_veg_merged %>%
  #pivot_longer(everything(), manes_to = "")
ggplot(df_veg_merged, aes(x=ALLTRANSITION)) +
  geom_bar(color="darkgreen",fill = "palegreen3") + 
  ggtitle("Length to Transition vs. Length of Overall Diet") +
  xlab("How Long Partitipants took to Transition")+
  ylab("Count")+
  facet_wrap('ALLLENGTH') +
  theme_grey(14) + 
  theme(text = element_text(size=9), legend.position = "none", plot.title = element_text(hjust = 0.5))
```


```{r}
df_incondichot <- read_csv('project_data/inconvenience_dichot.csv')
df_incondichot


df_incondichot$ALLINCONVENIENCE4D <- as.factor(df_incondichot$ALLINCONVENIENCE4D)
df_incondichot$ALLLENGTH <- as.integer(df_incondichot$ALLLENGTH)
mosaic(ALLLENGTH~ALLINCONVENIENCE4D, df_incondichot, direction=c("v","h"),main='Length of Diet & Difficulty Accessing Health Foods')
```

```{r}
df_incondichot$ALLINCONVENIENCE3D <- as.factor(df_incondichot$ALLINCONVENIENCE3D)
mosaic(ALLLENGTH~ALLINCONVENIENCE3D, df_incondichot, direction=c("v","h"),main='Length of Diet & Trouble Finding Restaurants')
```