# Conclusion

## Conclusions
### Restaurants
The period between April 2017 through July 2017 saw the highest increase of restaurant openings, with more than 2250. With the second greatest increase in openings occurred between January 2016-May 2016 with a little over 1750, and the third occurring between July 2015 and November 2015 with just over 750 restaurants in October 2015. The states in the Pacific Northwest region of the US have the fewest number of vegan/vegetarian restaurants including Alaska, with more densely populated states in the West such as California and Texas with the most restaurants, along with states in the NorthEast region ous the US. Based on the data, New York has the most vegan/vegetarian restaurants.

### Transitioning to a Vegan/Vegetarian Diet
The data does not suggest a relationship between Time to Transition and overall length of maintaining the vegan/vegetarian diet. Of the Indivduals that selected "5" or most difficulty transitioning to the diet, most adopted the diet between 20-40 years of age with the least having adopted the diet from ages 60 and older. Most of the distribution across time to fully transition lies between 20-40 years of age at adoption. 

### Length of Diet Maintenance
The data suggest that as the amount of time maintaining the diet increases, the that reports of experiencing difficulty in accessing health foods and vegan/vegetarian restaurants decreases. For example of those that only maintained their vegan/vegetarian diet for 0-3 months, they also reported the highest counts of difficulties. Whereas the counts of difficulty is least amongst those that maintained their diet for 6-9 years and more than 9 years. Overall, this suggests that there is a relationship between such difficulties and how long an individual may be able to maintain a vegan/vegetarian diet. Resource and availability are important factors towards going an extended period of time on such diet. Overall the data also demonstrates that most of the participants included in the study obtained bachelors degrees, and there is not a clear association between length of maintaining a vegan/vegetarian diet and education level.


## Limitations

While examining how the number of vegan/vegetarian restaurants opened over time, the data does not include openings prior to the 2015 time period, neither does it included updated data from 2019 through 2021. Having data collected prior to 2015 may help in our overall analysis by contributing to the larger picture of the changes that occurred. Data from 2019 to the present day may provide us with better insight as into the current changes in openings. For the graphs for which we examined Age at Vegan/Vegetarian Adoption and Difficulty in Transition Opinions, most of the participants in the study adopted a vegan/vegetarian diet between 20-40 years of age, with fewest participants that adopted that diet from 60 through 100 years of age. In addition, the datasets from Faunalytics from which we obtained insights froma survey and the dataset from Datafiniti are related in topic, however not in observations. Due to this we could not merge both datasets and make analyses. It is also very important to state that the data is skewed towards individuals who have obtained bachelors degrees and does not provide a complete representation of observations across individuals who have completed high school or less than high school - a more equally distributed dataset or stratified random sample would be needed to make best observations. 

## Future Work
As it stands we do not have any simple graphs that display the general counts per demographic variable and their respective levels to provide the audience with a more indepth examination of the nature of the data. While after examining our results it appears that most individuals surveyed through the Faunalytics study obtained bachelors degrees and adopted a vegan/vegetarian diet between ages 20-40 years, this would be best displayed via a simple graph. It would also be interesting to display the racial and religious demographics of this data to get a better sense of the individuals from which this data is being collected. In addition, investigating potential reasons behind increases in vegan/vegetarian restaurant openings would be valuable.

Our graph also does not include the changes in restaurant openings by state or city, therefore we currently do not have insight into where these openings occur.
