--- 
title: "Plant-Based Dining Trends"
author: "Sai Krupa Jangala, Kailande Cassamajor"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


In 2019 the Study of Current and Former Vegetarians and Vegans was conducted by Faunalytics. This study sought to investigate the factors that influence current and former vegans and vegetarians to adopt and sometimes give up their diets. In a report written by Animal Charity Evaluators, 2-6% of Americans self-identify as vegetarians. While individuals who identify as vegan or vegetarian are in the minority, it comes as no surprise that the percentage of self-identified vegetarians increased substantially between 2013 and 2018. Given such trends, this project also makes use of the Vegetarian & Vegan Dataset by Datafiniti through which we focus on the overall counts of vegan/vegetarian restaurants present within the dataset, including the cities with the highest prevalence of such restaurants.

Due to this interesting rise in individuals self-identifying as vegans and/or vegetarians, we were interested in examining potential trends in the opening of plant-based restaurants throughout the country over a certain time period. In addition to this we sought to investigate potential relationships between the length of a person's vegan/vegetarian diet and inconvenience factors.  We were also interested in what factors could have influenced how long it takes to transition to a vegan/vegetarian diet. For this project we sought to answer the following questions:

* Based on the Data, What is the Vegan/Vegetarian Restaurant Count Across States in the US?
* What Are the Top 25 Cities With the Most Vegan/Vegetarian Restaurants?
* What Were the Most Agreed with Inconvenience Reasons to a Vegan/Vegetarian Diet?
* How Many Vegan/Vegetarian Restaurants Opened Over Time? Are There Any Noticeable Trends?
* Is There A Relationship Between Time to Transition to Veganism & The Length of Time Maintaining the Diet?
* How Does Difficulty in Transition Opinions Differ Across Age Groups?
* What Are the Distributions for Age of Adoption Across Transition Time?
* What Are the Distributions for Age of Adoption by Length of Maintaining a Vegan/Vegetarian Diet?
* Is There a Relationship Between Length of Maintaining Vegan/Vegetarian Diet and Access to Health Foods & Vegan/Vegetarian Restaurant Options?

An Interactive Plot displaying the Counts for each of the inconvenience reasons for a vegan/vegetarian diet has been included. Conclusions based on extracted insights of our analysis, limitations and future possible work is also included.